# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `yard-kramdown` gem.
# Please instead update this file by running `bin/tapioca gem yard-kramdown`.


# source://yard-kramdown//lib/yard-kramdown.rb#1
module YARD; end

# source://yard-kramdown//lib/yard-kramdown.rb#2
module YARD::Templates; end

# source://yard-kramdown//lib/yard-kramdown.rb#3
module YARD::Templates::Helpers; end

# source://yard-kramdown//lib/yard-kramdown.rb#11
module YARD::Templates::Helpers::HtmlHelper
  include ::YARD::Templates::Helpers::ModuleHelper

  # source://yard-kramdown//lib/yard-kramdown.rb#12
  def html_markup_kramdown(text); end
end

# source://yard-kramdown//lib/yard-kramdown.rb#4
module YARD::Templates::Helpers::MarkupHelper; end
