# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `PoroGenerator`.
# Please instead update this file by running `bin/tapioca dsl PoroGenerator`.


class PoroGenerator
  sig { returns(T.nilable(T::Boolean)) }
  def minitest; end

  sig { returns(T.nilable(T::Boolean)) }
  def no_suffix; end

  sig { returns(T.nilable(T::Boolean)) }
  def rspec; end
end
