# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ServiceGenerator`.
# Please instead update this file by running `bin/tapioca dsl ServiceGenerator`.


class ServiceGenerator
  sig { returns(T.nilable(T::Boolean)) }
  def minitest; end

  sig { returns(T.nilable(T::Boolean)) }
  def no_suffix; end

  sig { returns(T.nilable(T::Boolean)) }
  def rspec; end
end
